don't store DDP model in fairseq nan detector
Summary:
I ran into an error with nan detector recently: f221506814
```
torch.nn.modules.module.ModuleAttributeError: 'AddJoinerSparse' object has no attribute '_parameters'
```
full log: P144224349

It seems to fail when we do a deepcopy of the joiner in our implementation of transducer transformer: https://fburl.com/diffusion/78jkfk2z

Very interestingly, it seems to be copying a DistributedDataParallel object! This seemed really weird, since a user module shouldn't really contain a reference to a DistributedDataParallel object.

After investigation this seems to be because of the backward hooks that `NanDetector` adds to the module. The backward hooks reference NanDetector, which references `model`, which is the `DistributedDataParallel` object.

The fix is then to not store a reference to the `DistributedDataParallel` in `NanDetector`

Reviewed By: zhengwy888

Differential Revision: D24058995

fbshipit-source-id: 48209339243d8b23b078274b780e850335839e89