Use safe_round in ctc reduce_metrics
Summary:
Validation step was failing with this error:
```
  File "/mnt/xarfuse/uid-188222/f6ace8b6-seed-f166b132-0f4f-40ae-8261-c83ec5d2e63c-ns-4026533670/fairseq/trainer.py", line 644, in valid_step
    logging_output = self._reduce_and_log_stats(logging_outputs, sample_size)
  File "/mnt/xarfuse/uid-188222/f6ace8b6-seed-f166b132-0f4f-40ae-8261-c83ec5d2e63c-ns-4026533670/fairseq/trainer.py", line 949, in _reduce_and_log_stats
    logging_output = agg.get_smoothed_values()
  File "/mnt/xarfuse/uid-188222/f6ace8b6-seed-f166b132-0f4f-40ae-8261-c83ec5d2e63c-ns-4026533670/fairseq/logging/meters.py", line 268, in get_smoothed_values
    for key in self.keys()
  File "/mnt/xarfuse/uid-188222/f6ace8b6-seed-f166b132-0f4f-40ae-8261-c83ec5d2e63c-ns-4026533670/fairseq/logging/meters.py", line 269, in <listcomp>
    if not key.startswith("_")
  File "/mnt/xarfuse/uid-188222/f6ace8b6-seed-f166b132-0f4f-40ae-8261-c83ec5d2e63c-ns-4026533670/fairseq/logging/meters.py", line 260, in get_smoothed_value
    return meter.fn(self)
  File "/mnt/xarfuse/uid-188222/f6ace8b6-seed-f166b132-0f4f-40ae-8261-c83ec5d2e63c-ns-4026533670/fairseq/criterions/ctc.py", line 234, in <lambda>
    if meters["_w_total"].sum > 0
TypeError: type Tensor doesn't define __round__ method

```
This issue was also raised in T71334670. Quoting Myle from https://fb.workplace.com/groups/fairseq/permalink/694410594696062/:
"Hmm, yeah, we now return tensors for multi-GPU since the stats are synced over GPU/NCCL. You can use utils.item(trainer.get_meter(...)) as a workaround."

Reviewed By: alexeib

Differential Revision: D23035154

fbshipit-source-id: 65537f3b5d9d1112d9e3a1964618ec524bc28378